# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/moto_sched

ifneq ($(filter m y,$(CONFIG_MTK_SCHED_VIP_TASK)),)
CONFIG_MOTO_MUTEX_INHERIT := y
CONFIG_MOTO_RWSEM_INHERIT := y
endif

obj-m += moto_sched.o

ifneq ($(filter m y,$(CONFIG_MOTO_MUTEX_INHERIT)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_MUTEX_INHERIT
endif

ifneq ($(filter m y,$(CONFIG_MOTO_RWSEM_INHERIT)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_RWSEM_INHERIT
endif

ifneq ($(filter m y,$(CONFIG_MOTO_FUTEX_INHERIT)),)
	EXTRA_CFLAGS += -DCONFIG_MOTO_FUTEX_INHERIT
endif

moto_sched-y := msched_main.o msched_sysfs.o msched_common.o

moto_sched-y += locking/locking_main.o
moto_sched-$(CONFIG_MOTO_MUTEX_INHERIT) += locking/mutex.o
moto_sched-$(CONFIG_MOTO_RWSEM_INHERIT) += locking/rwsem.o
moto_sched-$(CONFIG_MOTO_FUTEX_INHERIT) += locking/futex.o
