# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include

obj-m += aw_haptic_hv_v1_5.o
aw_haptic_hv_v1_5-objs := aw869x.o aw869xx.o aw8671x.o aw8672x.o aw8692x.o aw8693x.o haptic_hv.o
