EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/drivers/base

ifneq ($(filter m y,$(CONFIG_STK501xx_USB_CAL)),)
    EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

ifneq ($(filter m y,$(CONFIG_STK501xx_POWER_SUPPLY_ONLINE)),)
    EXTRA_CFLAGS += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

ifneq ($(filter m y,$(CONFIG_STK501xx_FLIP_CAL)),)
    EXTRA_CFLAGS += -DCONFIG_CAPSENSE_FLIP_CAL
endif

ifneq (,$(filter river%,$(TARGET_PRODUCT)))
    EXTRA_CFLAGS += -DCONFIG_CAPSENSE_USB_CAL
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

obj-m := stk501xx_sar.o
stk501xx_sar-objs := stk501xx.o stk501xx_qualcomm.o stk_common.o
