KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/$(KERNEL_VERSION_NAME)/drivers/base

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

obj-m := stk501xx_sar.o
stk501xx_sar-objs := stk501xx.o stk501xx_qualcomm.o stk_common.o
